---
# file: roles/aws/tasks/ubuntu_bionic.yaml.yaml

- name: Enable deb-src APT Repository
  apt_repository:
    repo: "deb-src http://archive.ubuntu.com/ubuntu bionic main"
    state: "present"
    update_cache: yes
  tags:
    - enable-src-repo