---
cloudimg_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
cloudimg_dest: /opt/noble-server-cloudimg-amd64.img
cloudimg_checksum: sha256:00786c0936a7dd91a6b07941ca60bb56652975e0e72f9dacf73c887ada420966

kubernetes_pod_network:
  # Calico CNI.
  cni: "calico"
  cidr: "192.168.0.0/16"

kubernetes_calico_version: "3.30.3"
calicovppctl_version: "3.30.0"

kubernetes_calico_resources:
  tigera-operator.yaml: https://raw.githubusercontent.com/projectcalico/calico/v{{ kubernetes_calico_version }}/manifests/tigera-operator.yaml
  operator-crds.yaml: https://raw.githubusercontent.com/projectcalico/calico/v{{ kubernetes_calico_version }}/manifests/operator-crds.yaml

calicovppctl_resource: https://raw.githubusercontent.com/projectcalico/vpp-dataplane/v{{ calicovppctl_version }}/test/scripts/vppdev.sh

deploy_state: present
