---
# file: roles/dpdk/meta/main.yaml

# desc: Install DPDK from stable branch and configure service.
# inst: DPDK
# conf: ?
# info: 1.0 - added role

dependencies: []

galaxy_info:
  role_name: dpdk
  author: fd.io
  description: DPDK for Linux.
  company: none
  license: "license (Apache)"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - dpdk
