---
# file: roles/dpdk/meta/main.yaml

dependencies: []

galaxy_info:
  role_name: dpdk
  author: fd.io
  description: DPDK for Linux.
  company: none
  license: "license (Apache)"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - dpdk
