---
# file: roles/consul/meta/main.yaml

# desc: Install consul from stable branch and configure service.
# inst: Consul
# conf: ?
# info: 1.0 - added role

dependencies: []
galaxy_info:
  role_name: consul
  author: fd.io
  description: Hashicrop Consul.
  company: none
  license: "license (Apache)"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - consul
