---
# file: roles/consul/meta/main.yaml

dependencies: []
galaxy_info:
  role_name: consul
  author: fd.io
  description: Hashicrop Consul.
  company: none
  license: "license (Apache)"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - consul
