---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-controller-cfg
  namespace: csit
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
      - "172.17.0.1:22379"

  sfc.conf: |
    sfc_controller_config_version: 1
    description: $$TEST_NAME$$
    host_entities:
      - name: vswitch
    sfc_entities:
      - name: vswitch-vnf1
        description: vswitch to VNF1 - memif
        type: 3
        bd_parms:
          flood: true
          unknown_unicast_flood: true
          forward: true
          learn: true
        elements:
          - container: vswitch
            port_label: $$VSWITCH_IF1$$
            etcd_vpp_switch_key: vswitch
            type: 5
          - container: vnf1
            port_label: port1
            etcd_vpp_switch_key: vswitch
            type: 2
      - name: vswitch-vnf4
        description: VNF4 to vswitch - memif
        type: 3
        bd_parms:
          flood: true
          unknown_unicast_flood: true
          forward: true
          learn: true
        elements:
          - container: vswitch
            port_label: $$VSWITCH_IF2$$
            etcd_vpp_switch_key: vswitch
            type: 5
          - container: vnf4
            port_label: port2
            etcd_vpp_switch_key: vswitch
            type: 2
      - name: vnf1-vnf2
        description: vnf1 to vnf2 via vswitch - memifs
        type: 5
        elements:
          - container: vnf1
            port_label: port2
            etcd_vpp_switch_key: vswitch
            type: 2
          - container: vnf2
            port_label: port1
            etcd_vpp_switch_key: vswitch
            type: 2
      - name: vnf2-vnf3
        description: vnf2 to vnf3 via vswitch memifs
        type: 5
        elements:
          - container: vnf2
            port_label: port2
            etcd_vpp_switch_key: vswitch
            type: 2
          - container: vnf3
            port_label: port1
            etcd_vpp_switch_key: vswitch
            type: 2
      - name: vnf3-vnf4
        description: vnf3 to vnf4 via vswitch memifs
        type: 5
        elements:
          - container: vnf3
            port_label: port2
            etcd_vpp_switch_key: vswitch
            type: 2
          - container: vnf4
            port_label: port1
            etcd_vpp_switch_key: vswitch
            type: 2

  vnf.conf: |
    vnf_plugin_config_version: 1
    description: VNF config
    vnf_entities:
      - name: vnf1
        container: vnf1
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf2
        container: vnf2
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf3
        container: vnf3
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf4
        container: vnf4
        l2xconnects:
          - port_labels:
            - port1
            - port2
