apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-agent-cfg
  namespace: csit
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
      - "172.17.0.1:22379"

  kafka.conf: |
    addrs:
      - "172.17.0.1:9092"

  telemetry.conf: |
    polling-interval: 30000000000
    disabled: true
