---
# file: host_vars/10.30.51.43.yaml

hostname: "s43-t29-tg1"
grub:
  audit: "0"
  default_hugepagesz: "2M hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=32768"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on,sm_on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-29,31-59,61-89,91-119,121-149,151-179,181-209,211-239"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-29,31-59,61-89,91-119,121-149,151-179,181-209,211-239"
  nosoftlockup: true
  no5lvl: true
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-29,31-59,61-89,91-119,121-149,151-179,181-209,211-239"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,30,60,90,120,150,180,210"
  vm:
    nr_hugepages: 32768
    max_map_count: 20000

inventory_ipmi_hostname: "10.30.50.43"
cpu_microarchitecture: "emeraldrapids"

intel_800_matrix: "dpdk24.07"
intel_dsa_matrix: true
intel_qat_matrix: true

docker_tg: true
docker_volumes:
  - source: "/usr/lib/firmware/"
    target: "/usr/lib/firmware/"