---
# file: host_vars/10.30.51.47.yaml

hostname: "s12-t31-sut2"
grub:
  audit: "0"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-27,29-55,57-83,85-111"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-27,29-55,57-83,85-111"
  nosoftlockup: True
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-27,29-55,57-83,85-111"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,28,56,84"
  vm:
    nr_hugepages: 36864
    max_map_count: 20000

inventory_ipmi_hostname: '10.30.50.44'
cpu_microarchitecture: "skylake"
