---
# file: host_vars/10.30.51.40.yaml

hostname: "s40-t28-sut1"
grub:
  audit: "0"
  default_hugepagesz: "2M hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=32768"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on,sm_on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-23,25-47,49-71,73-95,97-119,121-143,145-167,169-191"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-23,25-47,49-71,73-95,97-119,121-143,145-167,169-191"
  nosoftlockup: true
  no5lvl: true
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-23,25-47,49-71,73-95,97-119,121-143,145-167,169-191"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,24,48,72,96,120,144,168"
  vm:
    nr_hugepages: 32768
    max_map_count: 20000

inventory_ipmi_hostname: "10.30.50.40"
cpu_microarchitecture: "emeraldrapids"

intel_800_matrix: "dpdk24.07"
intel_dsa_matrix: true
intel_qat_matrix: true

docker_sut: true
docker_volumes:
  - source: "/dev/null"
    target: "/etc/sysctl.d/80-vpp.conf"
  - source: "/opt/boot/"
    target: "/opt/boot/"
  - source: "/opt/dpdk-25.07/"
    target: "/opt/dpdk-25.07/"
  - source: "/usr/bin/iperf3"
    target: "/usr/bin/iperf3"
  - source: "/usr/lib/x86_64-linux-gnu/libiperf.so.0"
    target: "/usr/lib/x86_64-linux-gnu/libiperf.so.0"
  - source: "/usr/lib/x86_64-linux-gnu/libiperf.so.0.0.0"
    target: "/usr/lib/x86_64-linux-gnu/libiperf.so.0.0.0"
  - source: "/var/run/docker.sock"
    target: "/var/run/docker.sock"
  - source: "/usr/lib/firmware/"
    target: "/usr/lib/firmware/"
  - source: "/usr/local/bin/adf_ctl"
    target: "/usr/local/bin/adf_ctl"
  - source: "/usr/bin/accel-config"
    target: "/usr/bin/accel-config"
  - source: "/usr/lib64/libaccel-config.so.1"
    target: "/usr/lib64/libaccel-config.so.1"
  - source: "/etc/accel-config"
    target: "/etc/accel-config"
  - source: "/etc/4xxx_dev0.conf"
    target: "/etc/4xxx_dev0.conf"
  - source: "/etc/4xxx_dev1.conf"
    target: "/etc/4xxx_dev1.conf"

# Calico
calico_sut: true
calico_corelist_workers: "2,3,4,5,98,99,100,101"
calico_uplink_interfaces:
  - interfaceName: "enp56s0np0"
    vppDriver: "avf"
    rx: 8
    rxMode: "polling"
    pci: "0000:38:00.0"
    ip_addr: "192.168.1.2/24"
    ip_route: "10.0.0.0/8 via 192.168.1.1"
  - interfaceName: "enp58s0np0"
    vppDriver: "avf"
    rx: 8
    rxMode: "polling"
    pci: "0000:3a:00.0"
    ip_addr: "192.168.2.2/24"
    ip_route: "20.0.0.0/8 via 192.168.2.1"