---
# file: host_vars/10.32.8.21.yaml

hostname: "s36-t28-tg1"
grub:
  audit: "0"
  default_hugepagesz: "2M hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=8192"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-27,29-55,57-83,85-111"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-27,29-55,57-83,85-111"
  nosoftlockup: true
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-27,29-55,57-83,85-111"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,28,56,84"
  vm:
    nr_hugepages: 8192
    max_map_count: 20000

inventory_ipmi_hostname: "10.30.55.21"
cpu_microarchitecture: "cascadelake"

intel_700_matrix: "dpdk21.02"
intel_800_matrix: "dpdk21.02"
mellanox_cx5_matrix: "dpdk21.02"
