---
# file: host_vars/10.30.51.82.yaml

hostname: "s72-t212-tg1"
grub:
  audit: "0"
  default_hugepagesz: "2M hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=32768"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-31,33-63,65-95,97-127"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-31,33-63,65-95,97-127"
  nosoftlockup: true
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-31,33-63,65-95,97-127"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,32,64,96"
  vm:
    nr_hugepages: 32768
    max_map_count: 20000

inventory_ipmi_hostname: "10.30.50.82"
cpu_microarchitecture: "icelake"

intel_700_matrix: "dpdk21.02"
intel_800_matrix: "dpdk21.02"
