---
# file: host_vars/10.30.51.52.yaml

hostname: "s52-t21-sut1"
grub:
  audit: "0"
  default_hugepagesz: "2M hugepagesz=1G hugepages=32 hugepagesz=2M hugepages=32768"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on,sm_on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-31,33-63,65-95,97-127"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-31,33-63,65-95,97-127"
  nosoftlockup: true
  no5lvl: true
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-31,33-63,65-95,97-127"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,32,64,96"
  vm:
    nr_hugepages: 32768
    max_map_count: 20000

inventory_ipmi_hostname: "10.30.50.52"
cpu_microarchitecture: "sapphirerapids"

mellanox_matrix: "dpdk24.07"
intel_dsa_matrix: true
intel_qat_matrix: true

docker_sut: true
docker_volumes:
  - source: "/usr/bin/ofed_info"
    target: "/usr/bin/ofed_info"
  - source: "/dev/null"
    target: "/etc/sysctl.d/80-vpp.conf"
  - source: "/opt/boot/"
    target: "/opt/boot/"
  - source: "/opt/dpdk-25.11/"
    target: "/opt/dpdk-25.11/"
  - source: "/usr/bin/iperf3"
    target: "/usr/bin/iperf3"
  - source: "/usr/lib/x86_64-linux-gnu/libiperf.so.0"
    target: "/usr/lib/x86_64-linux-gnu/libiperf.so.0"
  - source: "/usr/lib/x86_64-linux-gnu/libiperf.so.0.0.0"
    target: "/usr/lib/x86_64-linux-gnu/libiperf.so.0.0.0"
  - source: "/var/run/docker.sock"
    target: "/var/run/docker.sock"
  - source: "/usr/lib/firmware/"
    target: "/usr/lib/firmware/"
  - source: "/usr/local/bin/adf_ctl"
    target: "/usr/local/bin/adf_ctl"
  - source: "/etc/4xxx_dev0.conf"
    target: "/etc/4xxx_dev0.conf"
  - source: "/etc/4xxx_dev1.conf"
    target: "/etc/4xxx_dev1.conf"