---
# file: roles/vault/meta/main.yaml

# desc: Install vault from repo and configure service.
# inst: Vault
# conf: ?
# info: 1.0 - added role

dependencies: [ ]

galaxy_info:
  role_name: vault
  author: fd.io
  description: Hashicorp Vault.
  company: none
  license: "license (Apache)"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - vault
