apiVersion: v1
kind: Pod
metadata:
  name: sfc-controller
  namespace: csit
spec:
  containers:
    - name: "sfc-controller"
      image: ligato/prod_sfc_controller
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sfc-controller
        - -etcdv3-config=/opt/sfc-controller/dev/etcd.conf
        - -sfc-config=/opt/sfc-controller/dev/sfc.conf
      volumeMounts:
        - name: controller-config
          mountPath: /opt/sfc-controller/dev
  volumes:
    - name: controller-config
      configMap:
        name: sfc-controller-cfg