---
# file: group_vars/all.yaml

# General settings
ansible_python_interpreter: '/usr/bin/python2.7'
ansible_become_pass: '{{ inventory_sudo_pass }}'
# Domain is used in /etc/hosts file on target machine.
domain: 'linuxfoundation.org'

# Proxy settings: Uncomment and fill the proper values. These variables will be
# set globally by writing into /etc/environment file on target machine.
#proxy_env:
#  http_proxy: http://proxy.com:80
#  HTTP_PROXY: http://proxy.com:80
#  https_proxy: http://proxy.com:80
#  HTTPS_PROXY: http://proxy.com:80
#  ftp_proxy: http://proxy.com:80
#  FTP_PROXY: http://proxy.com:80
#  no_proxy: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}
#  NO_PROXY: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}

# Docker settings.
docker_edition: 'ce'
docker_channel: 'edge'
docker_version: '18.05.0'
docker_users: ['testuser']
docker_repository: 'deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}'
docker_apt_package_name: '{{ docker_version }}~{{ docker_edition }}~3-0~{{ ansible_distribution | lower }}'
docker_daemon_environment_http:
  - 'HTTP_PROXY={{ proxy_env.http_proxy }}'
  - 'NO_PROXY={{ proxy_env.no_proxy }}'
docker_daemon_environment_https:
  - 'HTTPS_PROXY={{ proxy_env.https_proxy }}'
  - 'NO_PROXY={{ proxy_env.no_proxy }}'

# Kubernetes settings.
kubernetes_channel: 'main'
kubernetes_version: '1.11.0-00'
kubernetes_repository: 'deb http://apt.kubernetes.io/ kubernetes-xenial {{ kubernetes_channel }}'
kubernetes_apt_package_name: '{{ kubernetes_version }}'
