---
# file: lf_inventory/group_vars/all.yaml

# provision via cobbler
provision_enabled: False
# name_servers_search is used in /etc/hosts file on target machine.
name_servers_search: 'linuxfoundation.org'
# name_servers is used in /etc/netplan/01-netcfg.yaml
name_servers: "1.1.1.1, 8.8.8.8"

# Proxy settings: Uncomment and fill the proper values. These variables will be
# set globally by writing into /etc/environment file on target machine.
#proxy_env:
#  http_proxy: http://proxy.com:80
#  HTTP_PROXY: http://proxy.com:80
#  https_proxy: http://proxy.com:80
#  HTTPS_PROXY: http://proxy.com:80
#  ftp_proxy: http://proxy.com:80
#  FTP_PROXY: http://proxy.com:80
#  no_proxy: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}
#  NO_PROXY: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}

# TRex settings.
trex:
  target_dir: '/opt'
  version: '2.61'

# DPDK settings.
dpdk:
  target_dir: '/opt'
  version: 'dpdk-19.02'
  url: 'https://fast.dpdk.org/rel'
  build_targets:
    aarch64: "arm64-armv8a"
    x86_64: "x86_64-native"

# WRK settings.
wrk:
  target_dir: '/opt'
  version: '4.0.2'

# Calibration settings.
jitter:
  directory: '/tmp/pma_tools'
  core: 7
  iterations: 30

# Mellanox OFED settings.
mellanox:
  version: '4.6-1.0.1.1'
