---
# file: roles/cleanup/tasks/vpp_device.yaml

- name: Reset vpp_device binary
  template:
   src: 'files/reset_vppdevice.sh'
   dest: '/usr/local/bin'
   owner: 'root'
   group: 'root'
   mode: '744'
  tags: reset-sriov

- name: Reset vpp_device
  raw: 'reset_vppdevice.sh --force'
  tags: reset-sriov
