---
# file: roles/vpp_device/tasks/main.yaml

- name: Load vfio-pci by default
  lineinfile:
    path: '/etc/modules'
    state: 'present'
    line: 'vfio-pci'
  tags: load-vfio-pci

- name: Copy csit-initialize-vfs.sh
  copy:
   src: 'files/csit-initialize-vfs.sh'
   dest: '/usr/local/bin/'
   owner: 'root'
   group: 'root'
   mode: '744'
  tags: copy-vf-script

- name: Copy csit-initialize-vfs-data.sh
  copy:
   src: 'files/{{ vfs_data_file }}'
   dest: '/usr/local/bin/csit-initialize-vfs-data.sh'
   owner: 'root'
   group: 'root'
   mode: '744'
  tags: copy-vf-data-script
  when: vfs_data_file is defined

- name: Copy default csit-initialize-vfs-data.sh
  copy:
   src: 'files/csit-initialize-vfs-default.sh'
   dest: '/usr/local/bin/csit-initialize-vfs-data.sh'
   owner: 'root'
   group: 'root'
   mode: '744'
  tags: copy-vf-data-script
  when: vfs_data_file is not defined

- name: Start csit-initialize-vfs.service
  copy:
   src: 'files/csit-initialize-vfs.service'
   dest: '/etc/systemd/system/'
   owner: 'root'
   group: 'root'
   mode: '644'
  notify:
    - 'Start csit-initialize-vfs.service'
  tags: start-vf-service

- meta: flush_handlers

- name: Set hugepages in GRUB
  lineinfile:
    path: '/etc/default/grub'
    state: 'present'
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="hugepagesz=2M hugepages={{ grub.nr_hugepages }}"'
  notify:
    - 'Update GRUB'
    - 'Reboot server'
  tags: set-grub

- meta: flush_handlers
