---
# file: roles/topology/tasks/main.yaml

- name: Create topology file
  template:
    src: "templates/topology_{{ cloud_topology }}.j2"
    dest: "../../../../topologies/available/{{ cloud_topology }}_{{ testbed_name }}.yaml"
  tags:
    - create-topology-file
