---
# file: roles/vpp_device/handlers/main.yaml

- name: Start csit-initialize-vfs.service
  systemd:
    enabled: yes
    state: started
    name: csit-initialize-vfs.service
  tags:
    - start-vf-service

- name: Update GRUB
  command: update-grub
  tags:
    - update-grub

- name: Reboot server
  reboot:
    reboot_timeout: 3600
  tags:
    - reboot-server
