---
# file: tasks/cleanup.yml

- name: reset network interface
  ansible.builtin.shell: |
    python3 /opt/dpdk/usertools/dpdk-devbind.py -b none {{ item.pci }} --force
    python3 /opt/dpdk/usertools/dpdk-devbind.py -b ice {{ item.pci }}
  loop: "{{ calico_uplink_interfaces }}"
  when:
    - calico_sut is defined
    - deploy_state == "absent"
  tags:
    - calico-cleanup