---
# file: nomad.yaml

- hosts: nomad
  remote_user: testuser
  become: yes
  become_user: root
  roles:
    - role: user_add
      tags: user_add
    - role: docker
      tags: docker
    - role: nomad
      tags: nomad
    - role: consul
      tags: consul