---
# file: site.yaml

- import_playbook: tg.yaml
  tags: tg

- import_playbook: sut.yaml
  tags: sut

#- import_playbook: vpp_device.yaml
#  tags: vpp-device

#- import_playbook: virl.yaml
#  tags: virl
