---
# file: sut.yaml

- hosts: sut
  remote_user: testuser
  become: yes
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
  roles:
    - role: baremetal
      tags: baremetal
    - role: common
      tags: common
    - role: kernel
      tags: kernel
    - role: mellanox
      tags: mellanox
    - role: docker
      tags: docker
    - role: vpp
      tags: vpp
    - role: dpdk
      tags: dpdk
    - role: nginx
      tags: nginx
    - role: kernel_vm
      tags: kernel_vm
    - role: csit_sut_image
      tags: csit_sut_image
    - role: performance_tuning
      tags: performance_tuning
    - role: cleanup
      tags: cleanup
    - role: calibration
      tags: calibration

- hosts: sut_aws
  remote_user: testuser
  become: yes
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
  roles:
    - role: user_add
      tags: user_add
    - role: common
      tags: common
    - role: vpp
      tags: vpp
    - role: dpdk
      tags: dpdk
    - role: aws
      tags: aws
    - role: iperf
      tags: iperf
    - role: nginx
      tags: nginx
    - role: docker
      tags: docker
    - role: cleanup
      tags: cleanup
    # TODO: 'Check Kernel Parameters' failing in
    # resources/tools/testbed-setup/ansible/roles/calibration/tasks/main.yaml
    # - role: calibration
    #   tags: calibration

- hosts: sut_azure
  become: yes
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
  roles:
    - role: user_add
      tags: user_add
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: vpp
      tags: vpp
    - role: azure
      tags: azure
    - role: iperf
      tags: iperf
    - role: nginx
      tags: nginx
    - role: dpdk
      tags: dpdk
    - role: cleanup
      tags: cleanup
    # TODO: 'Check Kernel Parameters' failing in
    # resources/tools/testbed-setup/ansible/roles/calibration/tasks/main.yaml
    # - role: calibration
    #   tags: calibration
