---
# file: sut_aws.yaml

- hosts: sut
  become: yes
  become_user: root
  roles:
    - role: user_add
      tags: user_add
    - role: common
      tags: common
    - role: sut
      tags: sut
    - role: dpdk
      tags: dpdk
    - role: aws
      tags: aws
    - role: iperf
      tags: iperf
    - role: docker
      tags: docker
    - role: cleanup
      tags: cleanup
    - role: calibration
      tags: calibration
