---
# file: tg_aws.yaml

- hosts: tg
  become: yes
  become_user: root
  roles:
    - role: user_add
      tags: user_add
    - role: common
      tags: common
    - role: dpdk
      tags: dpdk
    - role: aws
      tags: aws
    - role: tg
      tags: tg
    - role: iperf
      tags: iperf
    - role: trex
      tags: trex
    - role: ab
      tags: ab
    - role: docker
      tags: docker
    - role: cleanup
      tags: cleanup
#    - role: calibration
#      tags: calibration
