---
# file: tg_azure.yaml

- hosts: tg
  become: yes
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      gather_facts:
      tags:
        - always
  roles:
    - role: user_add
      tags: user_add
    - role: common
      tags: common
    - role: azure
      tags: azure
    - role: tg
      tags: tg
    - role: iperf
      tags: iperf
    - role: trex
      tags: trex
    - role: ab
      tags: ab
    - role: docker
      tags: docker
    - role: cleanup
      tags: cleanup
#    - role: calibration
#      tags: calibration
