---
# file: vpp_device.yaml

- hosts: vpp_device
  remote_user: testuser
  become: yes
  become_user: root
  roles:
    - role: common
      tags: common
    - role: vpp_device
      tags: vpp_device
    - role: cleanup
      tags: cleanup
