---
# file: vpp_device.yaml

- hosts: vpp_device
  remote_user: testuser
  become: yes
  become_user: root
  roles:
    - role: baremetal
      tags: baremetal
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: vpp_device
      tags: vpp_device
    - role: kernel_vm
      tags: kernel_vm
    - role: csit_sut_image
      tags: csit_sut_image
    - role: nomad
      tags: nomad
    - role: cleanup
      tags: cleanup
