---
# file: roles/common/defaults/main.yaml

packages: "{{ packages_base + packages_by_distro[ansible_distribution|lower][ansible_distribution_release] + packages_by_arch[ansible_machine] }}"

packages_base:
  - "autoconf"
  - "cgroup-tools"
  - "dkms"
  - "iperf3"
  - "linux-tools-common"
  - "ninja-build"
  - "qemu-system"
  - "socat"
  - "unzip"
  - "virtualenv"

packages_by_distro:
  ubuntu:
    bionic:
      - "build-essential"
      - "libpcap-dev"
      - "net-tools"
      - "python-all"
      - "python-apt"
      - "python-cffi"
      - "python-cffi-backend"
      - "python-dev"
      - "python-pip"
      - "python-setuptools"
      - "python3-all"
      - "python3-apt"
      - "python3-cffi"
      - "python3-cffi-backend"
      - "python3-dev"
      - "python3-pip"
      - "python3-pyelftools"
      - "python3-setuptools"
    focal:
      - "build-essential"
      - "libpcap-dev"
      - "net-tools"
      - "python3-all"
      - "python3-apt"
      - "python3-cffi"
      - "python3-cffi-backend"
      - "python3-dev"
      - "python3-pip"
      - "python3-pyelftools"
      - "python3-setuptools"

packages_by_arch:
  aarch64:
    - "gfortran"
    - "libblas-dev"
    - "libffi-dev"
    - "liblapack-dev"
    - "libssl-dev"
  x86_64:
    - []

# Proxy settings: Uncomment and fill the proper values. These variables will be
# set globally by writing into /etc/environment file on target machine.
#proxy_env:
#  http_proxy: http://proxy.com:80
#  HTTP_PROXY: http://proxy.com:80
#  https_proxy: http://proxy.com:80
#  HTTPS_PROXY: http://proxy.com:80
#  ftp_proxy: http://proxy.com:80
#  FTP_PROXY: http://proxy.com:80
#  no_proxy: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}
#  NO_PROXY: localhost,127.0.0.1,{{ ansible_default_ipv4.address }}