---
# file: roles/nomad/defaults/main.yaml

# Inst - Prerequisites.
packages: "{{ packages_base + packages_by_distro[ansible_distribution | lower] + packages_by_arch[ansible_machine] }}"

packages_base:
  - "cgroup-bin"
  - "curl"
  - "git"
  - "libcgroup1"
  - "unzip"
  - "htop"
packages_by_distro:
  ubuntu:
    - []
packages_by_arch:
  aarch64:
    - []
  x86_64:
    - []

# Inst - Download Nomad.
nomad_architecture_map:
  amd64: "amd64"
  x86_64: "amd64"
  armv7l: "arm"
  aarch64: "arm64"
  32-bit: "386"
  64-bit: "amd64"
nomad_architecture: "{{ nomad_architecture_map[ansible_architecture] }}"
nomad_version: "0.12.0"
nomad_pkg: "nomad_{{ nomad_version }}_linux_{{ nomad_architecture }}.zip"
nomad_zip_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/{{ nomad_pkg }}"

# Inst - System paths.
nomad_bin_dir: "/usr/local/bin"
nomad_config_dir: "/etc/nomad.d"
nomad_data_dir: "/var/nomad"
nomad_inst_dir: "/opt"
nomad_lockfile: "/var/lock/subsys/nomad"
nomad_run_dir: "/var/run/nomad"
nomad_ssl_dir: "/etc/nomad.d/ssl"

# Conf - Service.
nomad_node_role: "both"
nomad_restart_handler_state: "restarted"

# Conf - User and group.
nomad_group: "nomad"
nomad_group_state: "present"
nomad_manage_group: true
nomad_manage_user: true
nomad_user: "nomad"
nomad_user_groups: [ docker, nomad, root ]
nomad_user_state: "present"

# Conf - base.hcl
nomad_bind_addr: "0.0.0.0"
nomad_datacenter: "dc1"
nomad_disable_update_check: true
nomad_enable_debug: false
nomad_log_level: "INFO"
nomad_name: "{{ inventory_hostname }}"
nomad_region: "global"
nomad_syslog_enable: true

# Conf - tls.hcl
nomad_ca_file: "{{ nomad_ssl_dir }}/ca.pem"
nomad_cert_file: "{{ nomad_ssl_dir }}/nomad.pem"
nomad_http: false
nomad_key_file: "{{ nomad_ssl_dir }}/nomad-key.pem"
nomad_rpc: false

# Conf - client.hcl
nomad_certificates:
  - src: "{{ vault_nomad_ca_file }}"
    dest: "{{ nomad_ca_file }}"
  - src: "{{ vault_nomad_cert_file }}"
    dest: "{{ nomad_cert_file }}"
  - src: "{{ vault_nomad_key_file }}"
    dest: "{{ nomad_key_file }}"
nomad_node_class: ""
nomad_no_host_uuid: true
nomad_options: {}
nomad_servers: []
nomad_volumes: []

# Conf - server.hcl
nomad_bootstrap_expect: 2
nomad_encrypt: ""
nomad_retry_join: true

# Conf - telemetry.hcl
nomad_disable_hostname: false
nomad_collection_interval: 60s
nomad_use_node_name: false
nomad_publish_allocation_metrics: true
nomad_publish_node_metrics: true
nomad_backwards_compatible_metrics: false
nomad_telemetry_provider_parameters:
  prometheus_metrics: true

# Conf - custom.hcl
# empty
