---
# file: roles/docker/defaults/main.yaml

# Version options.
docker_edition: "ce"
docker_package: "docker-{{ docker_edition }}"
docker_package_state: latest

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Used only for Debian/Ubuntu.
docker_apt_release_channel: "stable"
docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_repository_state: present
docker_apt_ignore_key_error: true
docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_gpg_key_state: present

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: "0"
docker_yum_repo_enable_test: "0"
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

# A list of users who will be added to the docker group.
docker_users:
  - "testuser"

# Proxy settings.
docker_daemon_environment_http:
  - "HTTP_PROXY={{ proxy_env.http_proxy }}"
  - "NO_PROXY={{ proxy_env.no_proxy }}"
docker_daemon_environment_https:
  - "HTTPS_PROXY={{ proxy_env.https_proxy }}"
  - "NO_PROXY={{ proxy_env.no_proxy }}"