---
# file: host_vars/10.30.51.22.yaml

hostname: "t2-sut2"
grub:
  isolcpus: "1-17,19-35"
  nohz_full: "1-17,19-35"
  rcu_nocbs: "1-17,19-35"
sysctl:
  kernel:
    watchdog_cpumask: "0,18"
  vm:
    nr_hugepages: 36864
    max_map_count: 20000

cimc_hostname: '10.30.50.22'
cobbler_profile: '{{ ansible_distribution|lower }}-18.04-{{ ansible_machine }}'
