---
# file: host_vars/10.32.8.13.yaml

hostname: "s31-t35-sut2"
grub:
  isolcpus: "1-5"
  nohz_full: "1-5"
  rcu_nocbs: "1-5"
sysctl:
  kernel:
    watchdog_cpumask: "0"
  vm:
    nr_hugepages: 4096
    max_map_count: 20000

inventory_ipmi_hostname: '10.30.55.13'
cobbler_profile: 'ubuntu-18.04.2-server-x86_64'
cpu_microarchitecture: "denverton"
