---
# file: host_vars/10.30.51.24.yaml

hostname: "t3-tg1"
grub:
  isolcpus: "1-17,19-35"
  nohz_full: "1-17,19-35"
  rcu_nocbs: "1-17,19-35"
sysctl:
  kernel:
    watchdog_cpumask: "0,18"
  vm:
    nr_hugepages: 4096
    max_map_count: 20000

inventory_cimc_hostname: '10.30.50.24'
cobbler_profile: 'ubuntu-18.04.2-server-x86_64'
cpu_microarchitecture: "haswell"
