---
# file: host_vars/10.30.51.44.yaml

hostname: "s3-t21-sut1"
grub:
  isolcpus: "1-27,29-55,57-83,85-111"
  nohz_full: "1-27,29-55,57-83,85-111"
  rcu_nocbs: "1-27,29-55,57-83,85-111"
sysctl:
  kernel:
    watchdog_cpumask: "0,28,56,84"
  vm:
    nr_hugepages: 36864
    max_map_count: 20000

ipmi_hostname: '10.30.50.41'
cobbler_profile: '{{ ansible_distribution|lower }}-18.04-{{ ansible_machine }}'
