---
# file: host_vars/10.30.51.29.yaml

hostname: "t4-virl2"
virl_l2_start: "10.30.53.2"
virl_l2_end: "10.30.53.253"
virl_l2_gateway: "10.30.53.1"
virl_l2_network: "10.30.53.0/24"
virl_l2_ip: "10.30.53.254"
virl_public_port: "eth4"

cimc_hostname: '10.30.50.29'
cobbler_profile: 'ubuntu-18.04.2-server-x86_64'
