---
# file: host_vars/10.30.51.26.yaml

hostname: "t3-sut2"
grub:
  audit: "0"
  hpet: "disable"
  intel_idle.max_cstate: "1"
  intel_iommu: "on"
  intel_pstate: "disable"
  iommu: "pt"
  isolcpus: "1-17,19-35"
  mce: "off"
  nmi_watchdog: "0"
  nohz_full: "1-17,19-35"
  nosoftlockup: True
  numa_balancing: "disable"
  processor.max_cstate: "1"
  rcu_nocbs: "1-17,19-35"
  tsc: "reliable"
sysctl:
  kernel:
    watchdog_cpumask: "0,18"
  vm:
    nr_hugepages: 36864
    max_map_count: 20000

inventory_cimc_hostname: '10.30.50.26'
cpu_microarchitecture: "haswell"
