---
name: csit-vpp-perf-hoststack-daily

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  schedule:
    - cron:  "30 22 * * 0-4"

jobs:
  csit-vpp-perf-hoststack-daily:
    name: csit-vpp-perf-hoststack-daily-master-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=prod
      - fdio:os=${{ matrix.os }}
    timeout-minutes: 3600

    strategy:
      matrix:
        include:
          - node: 2n-grc
            os: ubuntu2404
            executor_arch: aarch64
          - node: 2n-icx
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-icx
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3na-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3nb-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-emr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-emr
            os: ubuntu2404
            executor_arch: x86_64
      fail-fast: false

    env:
      JOB_NAME: ${{ github.job }}-master-${{ matrix.node }}
      BUILD_TAG: ${{ github.job }}-master-${{ matrix.node }}-${{ github.run_id }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Run CSIT Bootstrap
        # yamllint disable-line rule:line-length
        uses: fdio/csit/.github/actions/csit-bootstrap@a372372ca8f89676c55631f8650468dfab86cc2a
        with:
          bootstrap_script: bootstrap_verify_perf.sh
          with_oper: true

      - name: AWS S3 Publish Logs
        if: ${{ always() }}
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/aws-s3-publish-logs@a28ad9abc70855292df1ea0d59829e814e78c2f4
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}
          # yamllint disable-line rule:line-length
          s3_path: ${{ github.job }}-master-${{ matrix.node }}/${{ github.run_id }}