---
name: csit-vpp-perf-mrr-weekly

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  #schedule:
  #  - cron:  "0 0 * * 1"
  workflow_dispatch:

jobs:
  csit-vpp-perf-mrr-weekly:
    name: csit-vpp-perf-mrr-weekly-master-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    timeout-minutes: 3600

    strategy:
      matrix:
        include:
          - node: 2n-aws
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-c6in
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-c7gn
            os: ubuntu2404
            executor_arch: aarch64

    env:
      JOB_NAME: ${{ github.job }}-master-${{ matrix.node }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@8930b575136625c5c8a47752192f9cd90202bea3

      - name: Run Performance Bootstrap
        uses: fdio/csit/.github/actions/csit-bootstrap@3835964003f751ea545d7926f46fade5e9e5da13
        with:
          bootstrap_script: bootstrap_verify_perf.sh
          with_oper: true

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/
          if-no-files-found: ignore

      - name: AWS S3 Publish Logs
        if: always()
        uses: pmikus/.github/.github/actions/aws-s3-publish-logs@8930b575136625c5c8a47752192f9cd90202bea3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}