---
name: csit-terraform-aws-eb-version

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  # yamllint disable-line rule:line-length
  group: verify-${{ github.workflow }}-${{ github.event.inputs.GERRIT_BRANCH }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-verify
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@8930b575136625c5c8a47752192f9cd90202bea3

      - name: Run Performance Bootstrap
        uses: pmikus/csit/.github/actions/csit-bootstrap@e29d99cde5a57e52dac8a07658960f4a95570861
        with:
          bootstrap_script: bootstrap_aws_eb_version_deploy.sh
          with_oper: false

  deploy:
    needs: verify
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-deploy
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup-executor-env@8930b575136625c5c8a47752192f9cd90202bea3

      - name: Run Performance Bootstrap
        uses: pmikus/csit/.github/actions/csit-bootstrap@e29d99cde5a57e52dac8a07658960f4a95570861
        with:
          bootstrap_script: bootstrap_aws_eb_version_deploy.sh
          with_oper: false
