---
name: csit-terraform-aws-eb-version

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=prod
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-verify
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Run CSIT Bootstrap
        # yamllint disable-line rule:line-length
        uses: fdio/csit/.github/actions/csit-bootstrap@a372372ca8f89676c55631f8650468dfab86cc2a
        with:
          bootstrap_script: bootstrap_aws_eb_version_verify.sh
          with_oper: false

  deploy:
    needs: verify
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=prod
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-deploy
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Run CSIT Bootstrap
        # yamllint disable-line rule:line-length
        uses: fdio/csit/.github/actions/csit-bootstrap@a372372ca8f89676c55631f8650468dfab86cc2a
        with:
          bootstrap_script: bootstrap_aws_eb_version_deploy.sh
          with_oper: false
